### ISSUE TITLE
Why did you stop at 12/31/20?

### ISSUE THREAD

**Issue by airalcorn2** [mbevand/mask-use#1]
Given that the winter 2020/2021 wave lasted well into the spring of 2021, the cutoff date of December 31st, 2020 seems pretty arbitrary. If you use a cutoff date of July 1st, 2021 (i.e., using a full year of data and going to the trough in cases), the R^2 drops to 0.116, which is remarkably low when considering all the variables mask-wearing is correlated with. Further, the top **six** counties in terms of cases per capita *all had a mask usage score of 75+*.

![chart](https://user-images.githubusercontent.com/1927770/166681168-1554b579-5db0-408c-9217-b3f8cfec44e1.png)

**Comment by mbevand** [comment]
It makes sense that doing the analysis on a **longer** period of time **decreases** the correlation, simply because people's mask wearing behavior changes over time. Their answer to a mask survey a year ago is much less relevant a year later. So, lacking more frequent up-to-date survey data, one must restrict the analysis to a relatively short time period.

Conversely, doing the analysis on a period of time that's too short also decreases the correlation, as many low-population counties have so few cases that a single cluster of COVID cases can significantly impact cases/capita, thus creating large variance in the data. For example if I restrict the analysis from 6 months to a 4-month period (ending October 31, 2020) I notice that half the counties have recorded fewer than 400 cases in this period. Things like a single church originating 200 cases would cause cases/capita to jump +50% for this county alone.

So analyzing over 6 months is a good compromise. This period covers a "full cycle": July 1 precedes by a few weeks the peak of the summer wave (cases peaked on July 24), and, similarly, December 31st precedes by a few weeks the peak of the winter wave (cases peaked on Jan 11). Maybe one could justify analyzing over 5 months, or 7 months. But outside of this range doesn't make much sense IMHO for the reasons explained above.

Lastly, I don't think that you can interpret anything meaningful of the top n=6 counties. The power of this analysis lies in the large dataset of n=3114 counties. Don't discard 99.8% of the data points!

**Comment by mbevand** [comment]
By the way, I initially found R²=0.240, but analyzing over 5 months make R² even higher (0.278):
![nov](https://user-images.githubusercontent.com/2995228/166744646-35d04042-6f5b-46c6-aee0-479faa38c595.png)

And analyzing over 7 months make R² smaller (0.167):
![jan](https://user-images.githubusercontent.com/2995228/166744666-1ff339bc-d931-4549-b2d6-ebb3b564381a.png)

If I wanted to cherry-pick I should have picked 5 months :smile:

**Comment by airalcorn2** [comment]
>simply because people's mask wearing behavior changes over time

Why would people's mask-wearing behavior change in the middle of a large wave? Cutting off in the middle of a wave makes the least sense to me.

>I don't think that you can interpret anything meaningful of the top n=6 counties.

You can conclude that there are important causal variables missing from the analysis, which, combined with the fact that the R^2 is not robust to minor changes in the dataset, makes any causal claims about the relationship between mask-wearing and cases per capita pretty tenuous.

**Comment by mbevand** [comment]
> Why would people's mask-wearing behavior change in the middle of a large wave.

I didn't say that.

> You can conclude that...

You can conclude anything after discarding 99.8% of data points.

> makes any causal claims

I do not make causal claims. I'm merely showing a correlation. Correlation ≠ causation.

> important causal variables missing from the analysis

Of course. I do mention it. See the README.md: "Note that this analysis does not control for other variables and is subject to confounding biases, for example people who report more frequent mask usage probably adhere to stronger social distancing protocols."
